#!/usr/bin/env ruby
require 'wc_styled'
option = ARGV[0]
file_path = ARGV[1]

opts = {
 l: false,
}
op = OptionParser.new
op.on('-l'){|v| opts[:l] = true}
op.parse(option)

WcStyled.run(file_path, opts)
